INSERT INTO USER_TABLE (ID, USER_NAME, USER_AGE, USER_COMMENT) VALUES (1000, 'dima', 25, 'comment 1')
INSERT INTO USER_TABLE (ID, USER_NAME, USER_AGE, USER_COMMENT) VALUES (1001, 'anton', 31, 'comment 21')
INSERT INTO USER_TABLE (ID, USER_NAME, USER_AGE, USER_COMMENT) VALUES (1002, 'vova', 27, 'comment 22')